spring:
  datasource:
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 20
      minimum-idle: 15
      pool-name: HikariConnectionPool
      idle-timeout: 600000
      max-lifetime: 1800000
      jdbc-url: jdbc:mysql://127.0.0.1:3306/real-estate
      username: vanhuy
      password: changeit@123
      driver-class-name: com.mysql.cj.jdbc.Driver
hibernate:
  dialect: org.hibernate.dialect.MySQL5Dialect
  show_sql: true
  hbm2ddl:
    auto: create-drop